# coding: utf-8

"""
    API de Usuarios

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.usuarios_get200_response import UsuariosGet200Response

class TestUsuariosGet200Response(unittest.TestCase):
    """UsuariosGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsuariosGet200Response:
        """Test UsuariosGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsuariosGet200Response`
        """
        model = UsuariosGet200Response()
        if include_optional:
            return UsuariosGet200Response(
                id = 56,
                nombre = '',
                apellido = '',
                telefono = ''
            )
        else:
            return UsuariosGet200Response(
        )
        """

    def testUsuariosGet200Response(self):
        """Test UsuariosGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
